"""Shared API matching rules for cross-framework mining scripts."""

from __future__ import annotations

import re
from typing import Union


NAMESPACES = {
    "torch": [
        "torch",
        "torch.nn",
        "torch.nn.functional",
        "torch.nn.init",
        "torch.linalg",
        "torch.special",
        "torch.fft",
        "torch.signal",
    ],
    "tensorflow": [
        "tensorflow",
        "tensorflow.math",
        "tensorflow.linalg",
        "tensorflow.nn",
        "tensorflow.image",
        "tensorflow.signal",
        "tensorflow.bitwise",
        "tensorflow.random",
        "tensorflow.keras.activations",
        "tensorflow.keras.losses",
        "tensorflow.keras.metrics",
        "tensorflow.keras.layers",
    ],
    "keras": [
        "keras.ops",
        "keras.activations",
        "keras.losses",
        "keras.metrics",
        "keras.layers",
        "keras.random",
        "keras.initializers",
        "keras.regularizers",
        "keras.optimizers",
    ],
    "jax": [
        "jax.numpy",
        "jax.numpy.fft",
        "jax.numpy.linalg",
        "jax.nn",
        "jax.lax",
        "jax.random",
        "jax.scipy.special",
        "jax.scipy.linalg",
        "jax.scipy.signal",
        "jax.scipy.stats",
    ],
    "numpy": [
        "numpy",
        "numpy.linalg",
        "numpy.fft",
        "numpy.random",
    ],
    "scipy": [
        "scipy.special",
        "scipy.linalg",
        "scipy.signal",
        "scipy.stats",
        "scipy.fft",
        "scipy.ndimage",
    ],
    "paddle": [
        "paddle",
        "paddle.nn",
        "paddle.nn.functional",
        "paddle.linalg",
        "paddle.fft",
        "paddle.tensor",
    ],
    "mxnet": [
        "mxnet.ndarray",
        "mxnet.ndarray.linalg",
        "mxnet.ndarray.random",
        "mxnet.numpy",
        "mxnet.numpy.linalg",
        "mxnet.numpy.random",
    ],
    "mindspore": [
        "mindspore",
        "mindspore.ops",
        "mindspore.ops.function",
        "mindspore.ops.functional",
        "mindspore.numpy",
        "mindspore.nn",
        "mindspore.mint",
        "mindspore.mint.nn",
        "mindspore.mint.nn.functional",
        "mindspore.mint.linalg",
        "mindspore.mint.special",
        "mindspore.scipy.linalg",
        "mindspore.scipy.ops",
    ],
    "chainer": [
        "chainer.functions",
        "chainer.links",
    ],
}


ALIASES = {
    "absolute": "abs",
    "acos": "arccos",
    "acosh": "arccosh",
    "asin": "arcsin",
    "asinh": "arcsinh",
    "atan": "arctan",
    "atanh": "arctanh",
    "atan2": "arctan2",
    "bitwise_left_shift": "left_shift",
    "bitwise_right_shift": "right_shift",
    "bitwise_invert": "bitwise_not",
    "invert": "bitwise_not",
    "greater": "greater",
    "gt": "greater",
    "greater_equal": "greater_equal",
    "ge": "greater_equal",
    "less": "less",
    "lt": "less",
    "less_equal": "less_equal",
    "le": "less_equal",
    "equal": "equal",
    "eq": "equal",
    "not_equal": "not_equal",
    "ne": "not_equal",
    "broadcast_equal": "equal",
    "broadcast_not_equal": "not_equal",
    "broadcast_greater": "greater",
    "broadcast_greater_equal": "greater_equal",
    "broadcast_lesser": "less",
    "broadcast_lesser_equal": "less_equal",
    "negative": "negative",
    "neg": "negative",
    "subtract": "subtract",
    "sub": "subtract",
    "broadcast_sub": "subtract",
    "broadcast_minus": "subtract",
    "multiply": "multiply",
    "mul": "multiply",
    "broadcast_mul": "multiply",
    "divide": "divide",
    "div": "divide",
    "broadcast_div": "divide",
    "truediv": "divide",
    "true_divide": "divide",
    "real_div": "divide",
    "elemwise_add": "add",
    "elemwise_sub": "subtract",
    "elemwise_mul": "multiply",
    "elemwise_div": "divide",
    "broadcast_add": "add",
    "pow": "power",
    "broadcast_power": "power",
    "maximum": "maximum",
    "broadcast_maximum": "maximum",
    "minimum": "minimum",
    "broadcast_minimum": "minimum",
    "amax": "max",
    "amin": "min",
    "arg_max": "argmax",
    "arg_min": "argmin",
    "reduce_all": "all",
    "reduce_any": "any",
    "reduce_logsumexp": "logsumexp",
    "reduce_max": "max",
    "reduce_mean": "mean",
    "reduce_min": "min",
    "reduce_prod": "prod",
    "reduce_sum": "sum",
    "reduce_std": "std",
    "reduce_variance": "var",
    "variance": "var",
    "cum_sum": "cumsum",
    "cum_prod": "cumprod",
    "cumulative_sum": "cumsum",
    "cumulative_prod": "cumprod",
    "concat": "concatenate",
    "cat": "concatenate",
    "concatenate_v2": "concatenate",
    "stack_v2": "stack",
    "unstack": "split",
    "expand_dims": "expand_dims",
    "unsqueeze": "expand_dims",
    "broadcast_dynamic_shape": "broadcast_shapes",
    "broadcast_static_shape": "broadcast_shapes",
    "moveaxis": "move_axis",
    "swapaxes": "swap_axes",
    "swapdims": "swap_axes",
    "permute": "transpose",
    "matrix_transpose": "transpose",
    "clip_by_value": "clip",
    "clamp": "clip",
    "bucketise": "bucketize",
    "count_nonzero": "count_nonzero",
    "where_v2": "where",
    "to_tensor": "convert_to_tensor",
    "greater_than": "greater",
    "less_than": "less",
    "logical_xor": "logical_xor",
    "top_k": "topk",
    "in_top_k": "topk",
    "matvec": "matmul_vector",
    "matrix_vector_product": "matmul_vector",
    "mv": "matmul_vector",
    "mm": "matmul",
    "bmm": "batch_matmul",
    "batch_matmul": "batch_matmul",
    "batch_dot": "batch_matmul",
    "batch_matmul_v2": "batch_matmul",
    "matrix_multiply": "matmul",
    "dot_general": "matmul",
    "einsum_path": "einsum",
    "matrix_determinant": "det",
    "determinant": "det",
    "matrix_inverse": "inv",
    "inverse": "inv",
    "matrix_solve": "solve",
    "triangular_solve": "solve_triangular",
    "matrix_triangular_solve": "solve_triangular",
    "cholesky_solve": "cho_solve",
    "matrix_rank": "matrix_rank",
    "linalg_norm": "norm",
    "svdvals": "svd",
    "eigvals": "eig",
    "eigvalsh": "eigh",
    "logdet": "slogdet",
    "fft": "fft",
    "ifft": "ifft",
    "fft2": "fft2",
    "ifft2": "ifft2",
    "rfft": "rfft",
    "irfft": "irfft",
    "rfft2": "rfft2",
    "irfft2": "irfft2",
    "relu6": "relu6",
    "leaky_relu": "leaky_relu",
    "log_sigmoid": "logsigmoid",
    "expit": "sigmoid",
    "hard_sigmoid": "hardsigmoid",
    "hard_silu": "hardswish",
    "hard_swish": "hardswish",
    "swish": "silu",
    "silu": "silu",
    "softmax_cross_entropy": "softmax_cross_entropy",
    "softmax_cross_entropy_with_logits": "softmax_cross_entropy",
    "sparse_softmax_cross_entropy_with_logits": "sparse_softmax_cross_entropy",
    "crossentropy": "cross_entropy",
    "cross_entropy_loss": "cross_entropy",
    "categorical_crossentropy": "categorical_cross_entropy",
    "categorical_crossentropy_loss": "categorical_cross_entropy",
    "sparse_categorical_crossentropy": "sparse_categorical_cross_entropy",
    "binary_crossentropy": "binary_cross_entropy",
    "binary_crossentropy_loss": "binary_cross_entropy",
    "bce_loss": "binary_cross_entropy",
    "binary_cross_entropy": "binary_cross_entropy",
    "bce_with_logits_loss": "binary_cross_entropy_with_logits",
    "binary_crossentropy_with_logits": "binary_cross_entropy_with_logits",
    "sigmoid_cross_entropy_with_logits": "binary_cross_entropy_with_logits",
    "mean_squared_error": "mse_loss",
    "mse": "mse_loss",
    "mse_loss": "mse_loss",
    "mean_absolute_error": "l1_loss",
    "mae": "l1_loss",
    "l1": "l1_loss",
    "kl_div": "kl_divergence",
    "kld": "kl_divergence",
    "kullback_leibler_divergence": "kl_divergence",
    "conv": "conv",
    "convolution": "conv",
    "conv1_d": "conv1d",
    "conv2_d": "conv2d",
    "conv3_d": "conv3d",
    "convolution1_d": "conv1d",
    "convolution2_d": "conv2d",
    "convolution3_d": "conv3d",
    "conv_transpose1_d": "conv_transpose1d",
    "conv_transpose2_d": "conv_transpose2d",
    "conv_transpose3_d": "conv_transpose3d",
    "conv1d_transpose": "conv_transpose1d",
    "conv2d_transpose": "conv_transpose2d",
    "conv3d_transpose": "conv_transpose3d",
    "deconv1d": "conv_transpose1d",
    "deconv2d": "conv_transpose2d",
    "deconv3d": "conv_transpose3d",
    "avg_pool": "avg_pool",
    "average_pooling": "avg_pool",
    "average_pooling1d": "avg_pool1d",
    "average_pooling2d": "avg_pool2d",
    "average_pooling3d": "avg_pool3d",
    "average_pool1d": "avg_pool1d",
    "average_pool2d": "avg_pool2d",
    "average_pool3d": "avg_pool3d",
    "avg_pooling1d": "avg_pool1d",
    "avg_pooling2d": "avg_pool2d",
    "avg_pooling3d": "avg_pool3d",
    "max_pooling1d": "max_pool1d",
    "max_pooling2d": "max_pool2d",
    "max_pooling3d": "max_pool3d",
    "average_pool": "avg_pool",
    "avg_pool1_d": "avg_pool1d",
    "avg_pool2_d": "avg_pool2d",
    "avg_pool3_d": "avg_pool3d",
    "average_pooling1_d": "avg_pool1d",
    "average_pooling2_d": "avg_pool2d",
    "average_pooling3_d": "avg_pool3d",
    "average_pool1_d": "avg_pool1d",
    "average_pool2_d": "avg_pool2d",
    "average_pool3_d": "avg_pool3d",
    "max_pool1_d": "max_pool1d",
    "max_pool2_d": "max_pool2d",
    "max_pool3_d": "max_pool3d",
    "max_pooling1_d": "max_pool1d",
    "max_pooling2_d": "max_pool2d",
    "max_pooling3_d": "max_pool3d",
    "adaptive_avg_pool1_d": "adaptive_avg_pool1d",
    "adaptive_avg_pool2_d": "adaptive_avg_pool2d",
    "adaptive_avg_pool3_d": "adaptive_avg_pool3d",
    "adaptive_max_pool1_d": "adaptive_max_pool1d",
    "adaptive_max_pool2_d": "adaptive_max_pool2d",
    "adaptive_max_pool3_d": "adaptive_max_pool3d",
    "global_average_pooling1_d": "global_avg_pool1d",
    "global_average_pooling2_d": "global_avg_pool2d",
    "global_average_pooling3_d": "global_avg_pool3d",
    "global_average_pooling1d": "global_avg_pool1d",
    "global_average_pooling2d": "global_avg_pool2d",
    "global_average_pooling3d": "global_avg_pool3d",
    "global_avg_pooling1d": "global_avg_pool1d",
    "global_avg_pooling2d": "global_avg_pool2d",
    "global_avg_pooling3d": "global_avg_pool3d",
    "global_max_pooling1d": "global_max_pool1d",
    "global_max_pooling2d": "global_max_pool2d",
    "global_max_pooling3d": "global_max_pool3d",
    "global_avg_pooling1_d": "global_avg_pool1d",
    "global_avg_pooling2_d": "global_avg_pool2d",
    "global_avg_pooling3_d": "global_avg_pool3d",
    "global_max_pooling1_d": "global_max_pool1d",
    "global_max_pooling2_d": "global_max_pool2d",
    "global_max_pooling3_d": "global_max_pool3d",
    "batch_normalization": "batch_norm",
    "batchnorm": "batch_norm",
    "layer_normalization": "layer_norm",
    "layernorm": "layer_norm",
    "group_normalization": "group_norm",
    "groupnorm": "group_norm",
    "instance_normalization": "instance_norm",
    "instancenorm": "instance_norm",
    "alpha_dropout": "alpha_dropout",
    "feature_alpha_dropout": "feature_alpha_dropout",
    "dense": "linear",
    "fully_connected": "linear",
    "flatten_layer": "flatten",
    "embedding_bag": "embedding_bag",
    "constant_pad1_d": "constant_pad1d",
    "constant_pad2_d": "constant_pad2d",
    "constant_pad3_d": "constant_pad3d",
    "zero_padding1_d": "zero_pad1d",
    "zero_padding2_d": "zero_pad2d",
    "zero_padding3_d": "zero_pad3d",
    "pad_v2": "pad",
    "random_normal": "normal",
    "standard_normal": "normal",
    "randn": "normal",
    "random_uniform": "uniform",
    "rand": "uniform",
    "randint": "random_integer",
    "random_integer": "random_integer",
    "onehot": "one_hot",
}


PREFIXES = (
    "tensorflow_keras_",
    "torch_nn_functional_",
    "torch_nn_",
    "tf_keras_",
    "nn_functional_",
    "functional_",
    "tensorflow_",
    "mindspore_",
    "paddle_",
    "chainer_",
    "mxnet_",
    "ndarray_",
    "numpy_",
    "scipy_",
    "torch_",
    "keras_",
    "jax_",
    "math_",
    "linalg_",
    "special_",
    "signal_",
    "random_",
    "ops_",
    "np_",
    "tf_",
    "nn_",
)


CATEGORY_TERMS = {
    "linalg": (
        "linalg",
        "svd",
        "eig",
        "eigh",
        "qr",
        "solve",
        "inv",
        "det",
        "cholesky",
        "norm",
        "matrix",
        "triangular",
    ),
    "nn": (
        "nn",
        "softmax",
        "softplus",
        "relu",
        "gelu",
        "sigmoid",
        "dropout",
        "conv",
        "pool",
        "batch_norm",
        "layer_norm",
        "embedding",
        "linear",
    ),
    "loss": (
        "loss",
        "cross_entropy",
        "binary_cross_entropy",
        "categorical_cross_entropy",
        "mse_loss",
        "l1_loss",
        "kl_divergence",
    ),
    "fft": ("fft", "rfft", "ifft"),
    "signal": ("signal", "stft", "istft", "window", "convolve"),
    "image": ("image", "resize", "crop", "flip", "rot90"),
    "random": (
        "random",
        "rand",
        "normal",
        "uniform",
        "bernoulli",
        "poisson",
        "gamma",
        "shuffle",
    ),
    "reduction": (
        "sum",
        "mean",
        "prod",
        "max",
        "min",
        "std",
        "var",
        "argmax",
        "argmin",
        "logsumexp",
        "count_nonzero",
    ),
    "shape": (
        "reshape",
        "squeeze",
        "expand_dims",
        "transpose",
        "concatenate",
        "stack",
        "split",
        "pad",
        "tile",
        "broadcast",
    ),
    "comparison": (
        "equal",
        "not_equal",
        "greater",
        "greater_equal",
        "less",
        "less_equal",
        "where",
    ),
}



PARAMETER_ROLE_ALIASES = {
    "a": "tensor",
    "array": "tensor",
    "arrays": "tensor",
    "arr": "tensor",
    "b": "tensor",
    "data": "tensor",
    "input": "tensor",
    "inputs": "tensor",
    "input_tensor": "tensor",
    "input_tensors": "tensor",
    "lhs": "tensor",
    "mat": "tensor",
    "mat1": "tensor",
    "mat2": "tensor",
    "matrix": "tensor",
    "other": "tensor",
    "rhs": "tensor",
    "tensor": "tensor",
    "tensors": "tensor",
    "value": "tensor",
    "values": "tensor",
    "x": "tensor",
    "y": "tensor",
    "z": "tensor",
    "axis": "axis",
    "axes": "axis",
    "dim": "axis",
    "dims": "axis",
    "dimension": "axis",
    "dimensions": "axis",
    "direction": "sort_order",
    "descending": "sort_order",
    "ascending": "sort_order",
    "largest": "sort_order",
    "sorted": "sort_order",
    "stable": "stability",
    "new_axis": "axis",
    "newaxis": "axis",
    "keepdim": "keepdim",
    "keepdims": "keepdim",
    "keep_dims": "keepdim",
    "dtype": "dtype",
    "out_dtype": "dtype",
    "output_dtype": "dtype",
    "shape": "shape",
    "shapes": "shape",
    "size": "shape",
    "sizes": "shape",
    "new_shape": "shape",
    "newshape": "shape",
    "target_shape": "shape",
    "output_shape": "shape",
    "k": "index",
    "idx": "index",
    "index": "index",
    "indices": "index",
    "indices_or_sections": "index",
    "repeats": "index",
    "n": "count",
    "num": "count",
    "num_segments": "count",
    "p": "probability",
    "prob": "probability",
    "probs": "probability",
    "probability": "probability",
    "rate": "probability",
    "training": "training",
    "train": "training",
    "is_training": "training",
    "reduction": "reduction",
    "reduction_axes": "axis",
    "ord": "norm_order",
    "order": "norm_order",
    "lower": "bound",
    "upper": "bound",
    "low": "bound",
    "high": "bound",
    "min": "bound",
    "max": "bound",
    "minimum": "bound",
    "maximum": "bound",
    "alpha": "scalar",
    "beta": "scalar",
    "eps": "scalar",
    "epsilon": "scalar",
    "fill_value": "scalar",
    "constant_values": "scalar",
    "kernel_size": "kernel",
    "kernel": "kernel",
    "stride": "stride",
    "strides": "stride",
    "padding": "padding",
    "pad": "padding",
    "dilation": "dilation",
    "dilations": "dilation",
    "groups": "groups",
    "mode": "mode",
    "seed": "seed",
    "key": "seed",
    "rng": "seed",
    "generator": "seed",
    "condition": "condition",
    "cond": "condition",
    "pred": "condition",
    "predicate": "condition",
    "fn": "callable",
    "func": "callable",
    "function": "callable",
    "body": "callable",
    "true_fn": "callable",
    "false_fn": "callable",
}


CONTROL_PARAMETER_ROLES = {
    "autocast",
    "compile",
    "debug",
    "device",
    "jit",
    "layer_name",
    "layout",
    "log_level",
    "name",
    "op_name",
    "out",
    "requires_grad",
    "validate_args",
    "validate_shape",
    "verbose",
}


def normalize_parameter_name(name: str) -> str:
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()
    name = name.replace("-", "_")
    name = re.sub(r"[^a-z0-9_]+", "_", name).strip("_")
    return name


def parameter_role(name: str) -> str:
    normalized = normalize_parameter_name(name)
    if normalized in {"self", "cls"}:
        return "control"
    if normalized in CONTROL_PARAMETER_ROLES:
        return "control"
    if normalized in PARAMETER_ROLE_ALIASES:
        return PARAMETER_ROLE_ALIASES[normalized]
    if normalized.endswith("_axis") or normalized.endswith("_axes"):
        return "axis"
    if normalized.endswith("_shape") or normalized.endswith("_size"):
        return "shape"
    if normalized.endswith("_dtype"):
        return "dtype"
    if normalized.startswith("input") or normalized.startswith("tensor"):
        return "tensor"
    if normalized.startswith("axis") or normalized.startswith("dim"):
        return "axis"
    if normalized.startswith("keepdim"):
        return "keepdim"
    if normalized.startswith("seed") or normalized.endswith("_seed"):
        return "seed"
    if normalized.startswith("is_") or normalized.startswith("use_"):
        return "flag"
    return f"param:{normalized}"


def parameter_roles(names: Union[tuple[str, ...], list[str]], *, include_control: bool = False) -> tuple[str, ...]:
    roles = []
    for name in names:
        role = parameter_role(name)
        if role == "control" and not include_control:
            continue
        roles.append(role)
    return tuple(roles)


def role_jaccard(left: Union[tuple[str, ...], list[str]], right: Union[tuple[str, ...], list[str]]) -> float:
    left_set = set(left)
    right_set = set(right)
    if not left_set and not right_set:
        return 1.0
    if not left_set or not right_set:
        return 0.0
    return len(left_set & right_set) / len(left_set | right_set)


def normalize_name(name: str, use_aliases: bool = True) -> str:
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()
    name = name.replace("-", "_")
    name = re.sub(r"[^a-z0-9_]+", "_", name).strip("_")
    name = re.sub(r"([0-9])_d([a-z])", r"\1d_\2", name)
    name = re.sub(r"([0-9])_d(\b|_)", r"\1d\2", name)
    name = re.sub(r"_v[0-9]+$", "", name)
    name = re.sub(r"_eager_fallback$", "", name)
    previous = None
    while previous != name:
        previous = name
        for prefix in PREFIXES:
            if name.startswith(prefix):
                name = name[len(prefix) :]
                break
    if not use_aliases:
        return name
    for _ in range(4):
        mapped = ALIASES.get(name)
        if mapped is None or mapped == name:
            return name
        name = mapped
    return name
